options:
  platform:     psx
  basename:     batini
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/BATTLE/BATINI.X.dec
  asm_path:     asm/us/battle
  asset_path:   assets/us/battle
  src_path:     src/battle
  ld_script_path: build/us/batini.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.batini.txt
    - config/sym_export_battle.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.batini.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.batini.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  migrate_rodata_to_functions: true
  disassemble_all: true
  global_vram_start: 0x801B0000
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: 2771b06f7249d34ed8a4f8c94e6047f70278e17c
segments:
  - name: batini
    type: code
    start: 0
    vram:  0x801B0000
    align: 4
    subalign: 4
    subsegments:
      - [0, .rodata, batini]
      - [0x50, c, batini]
  - [0x27B4]
