options:
  platform:     psx
  basename:     battle
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/BATTLE/BATTLE.X.dec
  asm_path:     asm/us/battle
  asset_path:   assets/us/battle
  src_path:     src/battle
  ld_script_path: build/us/battle.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.battle.txt
    - config/sym_battle_import.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.battle.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.battle.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x800A0000
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: c82690f814b18664c3b2d024f4edeea5743995d9
segments:
  - name: battle
    type: code
    start: 0
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1798, c, battle]
      - [0x47A38, data]
  - [0x538AC]
