options:
  platform:     psx
  basename:     brom
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/BATTLE/BROM.X.dec
  asm_path:     asm/us/brom
  asset_path:   assets/us/brom
  src_path:     src/brom
  ld_script_path: build/us/brom.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.brom.us.txt
    - config/sym_export.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.brom.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.brom.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x800A0000
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: ebc7a6559f677d1caef8c5db5fd884fd9e0ab156
segments:
  - name: brom
    type: code
    start: 0
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, brom]
      - [0x6B4, data]
  - [0x6CC]
