options:
  platform:     psx
  basename:     dschange
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/FIELD/DSCHANGE.X
  asm_path:     asm/us/dschange
  asset_path:   assets/us/dschange
  src_path:     src/dschange
  ld_script_path: build/us/dschange.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/sym_extern.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x800A0000
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: e884441c5ceacdeb94e16a603b73ca53706078e8
segments:
  - name: dschange
    type: code
    start: 0
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, dschange]
      - [0x1580, data]
      - [0x15E0, bss]
  - [0x1774]
