options:
  platform:     psx
  basename:     ending
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/FIELD/ENDING.X
  asm_path:     asm/us/ending
  asset_path:   assets/us/ending
  src_path:     src/ending
  ld_script_path: build/us/ending.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.ending.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.ending.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.ending.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x800A0000
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: 1b3fbf999913024209b23a1bb8a6874a66fc19ba
segments:
  - name: ending
    type: code
    start: 0
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, ending]
      - [0x3934, data]
      - [0x6524, bss]
  - [0xF414]
