options:
  platform:     psx
  basename:     field
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/FIELD/FIELD.BIN.dec
  asm_path:     asm/us/field
  asset_path:   assets/us/field
  src_path:     src/field
  ld_script_path: build/us/field.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.field.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.field.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.field.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  migrate_rodata_to_functions: true
  disassemble_all: true
  global_vram_start: 0x800A0000
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: 9d4dc1688526f48a5e0706228e6a751d01871396
segments:
  - name: field
    type: code
    start: 0
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, field]
      - [0x1368, c, field]
      - [0x3A5B8, data]
  - [0x40748]
