options:
  platform:     psx
  basename:     bginmenu
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/MENU/BGINMENU.MNU
  asm_path:     asm/us/menu
  asset_path:   assets/us/menu
  src_path:     src/menu
  ld_script_path: build/us/bginmenu.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.bginmenu.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.bginmenu.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.bginmenu.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x801D0000
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: af17d71fa4738e53ec50df5d15d992a355500223
segments:
  - name: bginmenu
    type: code
    start: 0
    vram:  0x801D0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, c, bginmenu]
      - [0x7F0, data]
      - [0x860, bss]
  - [0x898]
