options:
  platform:     psx
  basename:     cnfgmenu
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/MENU/CNFGMENU.MNU
  asm_path:     asm/us/menu
  asset_path:   assets/us/menu
  src_path:     src/menu
  ld_script_path: build/us/cnfgmenu.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.cnfgmenu.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.cnfgmenu.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.cnfgmenu.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x801D0000
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: 20450f6e53a204f0f3b251a3864f125bc7b27bb6
segments:
  - name: cnfgmenu
    type: code
    start: 0
    vram:  0x801D0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, cnfgmenu]
      - [0x40, c, cnfgmenu]
      - [0x1AA8, .data, cnfgmenu]
      - [0x24CC, .bss, cnfgmenu]
  - [0x2538]
