options:
  platform:     psx
  basename:     savemenu
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/MENU/SAVEMENU.MNU
  asm_path:     asm/us/menu
  asset_path:   assets/us/menu
  src_path:     src/menu
  ld_script_path: build/us/savemenu.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.savemenu.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.savemenu.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.savemenu.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x801D0000
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: 430d54dbe01d9a0c670b1d2d2b5c642bdd1b3199
segments:
  - name: savemenu
    type: code
    start: 0
    vram:  0x801D0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .rodata, savemenu]
      - [0x3B8, .rodata, title]
      - [0x408, c, savemenu]
      - [0x2B58, c, title]
      - [0x4EC4, data]
      - [0x12C78, .data, savemenu]
      - [0x13650, data]
      - [0x13698, bss]
  - [0x1BC44]
