/* AUTO-GENERATED by automation/generate_decls.py — do not edit manually */
/* Per-module declarations for 'world' — only valid in world m2c context */
/* struct types referenced here are defined by the module's own preprocessed headers */

#include "common.h"

s32 func_800A1D14(void);
void func_800A2040(void);
s32 func_800A21A4(void);
s32 func_800A31E8(void);
s32 func_800A32F4(void);
void func_800A368C(s32 arg0);
void func_800A38C8(void);
void func_800A3908(void);
void func_800A3DFC(void);
void func_800A3E4C(void);
void func_800A3E9C(s32 arg0);
void func_800A40B8(s32 arg0);
void func_800A41E8(s32 arg0);
void func_800A4494(s32 arg0);
void func_800A44A4(s32 arg0);
void func_800A44B4(s32 arg0);
void func_800A45C4(s32 arg0);
void func_800A45D4(s32 arg0);
void func_800A45E4(s32 arg0);
s32 func_800A45F4(void);
void func_800A6C00(s32 arg0);
void func_800A7F18(void);
s32 func_800A82F0(void);
void func_800A8888(s32 arg0);
void func_800A8F74(void);
void func_800A8FA0(void);
s32 func_800A921C(s32 arg0, u8 arg1);
void func_800A9678(s16 arg0);
void func_800A96A4(s16 arg0);
void func_800A9A04(s8 arg0);
void func_800A9A24(s16 arg0);
void func_800A9D5C(s32 arg0);
void func_800A9D88(s32 arg0);
void func_800ADC70(void);
s32 func_800AE628(void);
void func_800AF0A0(s32 arg0);
s32 func_800AF96C(s32 arg0);
s32 func_800B0240(void);
void func_800B28CC(s32 arg0);
void func_800B64A0(void);
void func_800B6AEC(void);
void func_800B6DCC(void);
void func_800B7134(void);
s32 func_800B7200(void);
void func_800B76A8(void);
void func_800B7820(void);
s32 func_800B785C(void);
s32 func_800B786C(void);
void func_800B7B1C(u8 arg0);
u16 func_800B7B3C(void);
u8 func_800B7BA0(void);
u8 func_800B7BC0(void);
void func_800B7C1C(void);
s32 func_800BBA44(void);
void func_800BBC4C(void);
s16 func_800BCA38(void);
