/* AUTO-GENERATED by automation/generate_decls.py — do not edit manually */
/* Per-module declarations for 'field' — only valid in field m2c context */
/* struct types referenced here are defined by the module's own preprocessed headers */

#include "common.h"

void func_800A1498(void);
void func_800AB2AC(void);
void func_800BA65C(s32 arg0);
s32 func_800BEE10(s16 arg0, s16 arg1);
s32 func_800C0B54(void);
void func_800C2CA8(void);
void func_800C49EC(void);
void func_800C4A40(void);
void func_800C4A94(void);
