/* AUTO-GENERATED by automation/generate_decls.py — do not edit manually */
/* Per-module declarations for 'menu' — only valid in menu m2c context */
/* struct types referenced here are defined by the module's own preprocessed headers */

#include "common.h"

void func_801D0000(void);
void func_801D00C4(void);
s32 func_801D01C4(s32 arg0);
void func_801D05C0(u8 arg0);
void func_801D05C4(s32 arg0);
void func_801D069C(void);
int func_801D06B0(s32 arg0);
void func_801D0704(s32 arg0);
s32 func_801D1774(void);
u16 func_801D1950(u16 len, u8* data);
void func_801D19C4(void);
void func_801D1BA4(void);
u16 func_801D1C2C(s32 arg0);
s32 func_801D2184(s8 arg0);
void func_801D21F0(u8* arg0, u8* arg1);
void func_801D3668(s32 arg0);
s32 func_801D3698(s32 arg0, s32 arg1);
void func_801D370C(s32 x, s32 y, s32 slot_no);
s32 func_801D4CC0(void);
