/* AUTO-GENERATED by automation/generate_decls.py — do not edit manually */
/* Per-module declarations for 'magic' — only valid in magic m2c context */
/* struct types referenced here are defined by the module's own preprocessed headers */

#include "common.h"

void func_801B0000(int arg0, int arg1);
